server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

grafanaConfig:
  headers:
    - name: Authorization
      value: Bearer eyJrIjoiWkxRWEJPS3ZUNURUbTlsQ2VEalVQUGpLSDhZZW9RMGgiLCJuIjoib3B0aW1pemVyIiwiaWQiOjF9
  url:
  prefix: local.prod

threadPoolConfig:
  enabled : false
  thresholdMinUsagePercentage: 50
  thresholdMaxUsagePercentage: 70
  queryDurationInHours: 1
  initialDelayInSeconds: 2
  intervalInSeconds: 86400
  reduceByThreshold: 50
  extendByThreshold: 50

mesosMonitorConfig:
  enabled : true
  queryDurationInHours: 11
  initialDelayInSeconds: 2
  intervalInSeconds: 86400
  extractionStrategy: MAX
  mesosEndpoint:
  cpuThresholds:
    enabled: true
    minResourcePercentage: 50
    maxResourcePercentage: 70
    reduceThreshold: 4
    extendThreshold: 4
    maxResourcesAllocatedPercentage: 160
    extendThresholdPercentage: 120
    defaultResources: 2
  memoryThresholds:
    enabled: false
    minResourcePercentage: 50
    maxResourcePercentage: 70
    reduceThreshold: 50
    extendThreshold: 50

serviceConfigs:
  - service: foxtrot-config
    ownerEmail: nitish.goyal@phonepe.com

mailConfig:
  from:
  host:
  port: 25
  defaultOwnersEnabled: true
  defaultOwnersEmails: nitishgoyal13@gmail.com

logging:
  level: INFO

clusters:
  - api