server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

grafannaConfig:
  headers:
    - name: Authorization
      value: Bearer eyJrIjoiWkxRWEJPS3ZUNURUbTlsQ2VEalVQUGpLSDhZZW9RMGgiLCJuIjoib3B0aW1pemVyIiwiaWQiOjF9

threadPoolConfig:
  thresholdUsagePercentage: 60
  queryDurationInHours: 192
  initialDelayInSeconds: 2
  intervalInSeconds: 86400

serviceConfigs:
  - service: foxtrot-config
    ownerEmail: mudit.g@phonepe.com
  - service: symphony-irctc-pool
    ownerEmail: mudit.g@phonepe.com

mail:
  from: noreply@phonepe.com
  host: ops-jump001.phonepe.nm1
  port: 25
  user: AKIAJLCWHAOEDK4ZDOGQ
  password: AgjCxNI68hrnj6bIzuJCiZBlDXW+TioRoU11++Yx97

logging:
  level: INFO
