server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

grafanaConfig:
  headers:
    - name: Authorization
      value: Bearer eyJrIjoiWkxRWEJPS3ZUNURUbTlsQ2VEalVQUGpLSDhZZW9RMGgiLCJuIjoib3B0aW1pemVyIiwiaWQiOjF9
  url: http://prd-grafana001.phonepe.nm1/api/datasources/proxy/10/query?db=riemann_metrics&q=%s
  prefix: phonepe.prod

threadPoolConfig:
  enabled : false
  thresholdMinUsagePercentage: 50
  thresholdMaxUsagePercentage: 70
  queryDurationInHours: 192
  initialDelayInSeconds: 2
  intervalInSeconds: 86400
  reduceByThreshold: 50
  extendByThreshold: 50

mesosMonitorConfig:
  enabled : true
  queryDurationInHours: 192
  initialDelayInSeconds: 2
  intervalInSeconds: 86400
  extractionStrategy: MAX
  mesosEndpoint: http://stg-appmesosm101.phonepe.nm2:8080
  cpuThresholds:
    enabled: true
    minResourcePercentage: 50
    maxResourcePercentage: 70
    reduceThreshold: 5
    extendThreshold: 5
  memoryThresholds:
    enabled: false
    minResourcePercentage: 50
    maxResourcePercentage: 70
    reduceThreshold: 50
    extendThreshold: 50

serviceConfigs:
  - service: tstore
    ownerEmail: achanta.vamsi@phonepe.com, tushar.naik@phonepe.com

mailConfig:
  from: noreply@phonepe.com
  host: stg-smtp001.phonepe.nm2
  port: 25
  defaultOwnersEnabled: true
  defaultOwnersEmails: nitish.goyal@phonepe.com

logging:
  level: INFO

clusters:
  - api