server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

grafanaConfig:
  headers:
    - name: Authorization
      value: Bearer eyJrIjoiWkxRWEJPS3ZUNURUbTlsQ2VEalVQUGpLSDhZZW9RMGgiLCJuIjoib3B0aW1pemVyIiwiaWQiOjF9
  url: http://prd-grafana001.phonepe.nm1/api/datasources/proxy/10/query?db=riemann_metrics&q=%s
  prefix: phonepe.prod.api.HystrixThreadPool

threadPoolConfig:
  thresholdMinUsagePercentage: 50
  thresholdMaxUsagePercentage: 70
  queryDurationInHours: 192
  initialDelayInSeconds: 2
  intervalInSeconds: 86400
  reduceByThreshold: 50
  extendByThreshold: 50

serviceConfigs:
  - service: tstore
    ownerEmail: achanta.vamsi@phonepe.com, tushar.naik@phonepe.com
  - service: foxtrot-config
    ownerEmail: nitish.goyal@phonepe.com
  - service: sessionServiceDb
    ownerEmail: sudhir.singh@phonepe.com
  - service: symphony-railservices-pool
    ownerEmail: durgaprasad.m@phonepe.com, symphony-oncall@phonepe.com
  - service: keystore
    ownerEmail: tushar.naik@phonepe.com
  - service: iris-queries
    ownerEmail: praveen.k@phonepe.com
  - service: mandates-db
    ownerEmail: durgaprasad.m@phonepe.com, symphony-oncall@phonepe.com
  - service: oculusSessionService
    ownerEmail: sudhir.singh@phonepe.com
  - service: nexus_callbacks
    ownerEmail: sarang.shravagi@phonepe.com, santosh.patil@phonepe.com
  - service: urlshortener
    ownerEmail: santanu@phonepe.com
  - service: external
    ownerEmail: vibhor.singhal@phonepe.com, nishant_mittal@phonepe.com, merchant-core@phonepe.com
  - service: digigold_external_service_queries
    ownerEmail: santosh.patil@phonepe.com
  - service: feed-common
    ownerEmail: tushar.naik@phonepe.com
  - service: merchant-service-db
    ownerEmail: vibhor.singhal@phonepe.com, nishant_mittal@phonepe.com, merchant-core@phonepe.com
  - service: sessionServiceProxy
    ownerEmail: sudhir.singh@phonepe.com
  - service: symphony-internal-pool
    ownerEmail: durgaprasad.m@phonepe.com, symphony-oncall@phonepe.com
  - service: symphony-redbus-pool
    ownerEmail: durgaprasad.m@phonepe.com, symphony-oncall@phonepe.com
  - service: mandate
    ownerEmail: durgaprasad.m@phonepe.com, symphony-oncall@phonepe.com
  - service: payments
    ownerEmail: rishabh@phonepe.com, payments-dev@phonepe.com
  - service: users-db
    ownerEmail: tushar.naik@phonepe.com, shashank.g@phonepe.com
  - service: clockwork
    ownerEmail: tushar.naik@phonepe.com
  - service: oculusProxyServices
    ownerEmail: sudhir.singh@phonepe.com
  - service: plutus-events-ing	estion
    ownerEmail: accounting@phonepe.com
  - service: nexus_promise
    ownerEmail: sarang.shravagi@phonepe.com, santosh.patil@phonepe.com
  - service: session-service
    ownerEmail: sudhir.singh@phonepe.com
  - service: geoservice-api
    ownerEmail: mayank.rathi@phonepe.com
  - service: symphony-commute-pool
    ownerEmail: durgaprasad.m@phonepe.com, symphony-oncall@phonepe.com
  - service: wallet
    ownerEmail: rishabh@phonepe.com, tushar@phonepe.com, payments-dev@phonepe.com
  - service: sessionServiceOnboarding
    ownerEmail: sudhir.singh@phonepe.com
  - service: catalogue-pool
    ownerEmail: durgaprasad.m@phonepe.com, symphony-oncall@phonepe.com
  - service: vault
    ownerEmail: phaneesh@phonepe.com, achanta.vamsi@phonepe.com
  - service: scroll
    ownerEmail: tushar.naik@phonepe.com
  - service: mercedes
    ownerEmail: mohammed.irfanulla@phonepe.com, nayanava.de@phonepe.com, offers-oncall@phonepe.com
  - service: nexus_fulfill
    ownerEmail: sarang.shravagi@phonepe.com, santosh.patil@phonepe.com
  - service: mystique
    ownerEmail: santanu@phonepe.com
  - service: extwallet-meta
    ownerEmail: rishabh@phonepe.com, tushar@phonepe.com, payments-dev@phonepe.com
  - service: hop
    ownerEmail: tushar.naik@phonepe.com, shashank.g@phonepe.com
  - service: banisher
    ownerEmail: shashank.g@phonepe.com
  - service: samsara-pool
    ownerEmail: durgaprasad.m@phonepe.com, symphony-oncall@phonepe.com
  - service: nexus_service_provider_queries
    ownerEmail: sarang.shravagi@phonepe.com, santosh.patil@phonepe.com
  - service: nexus_db_updates
    ownerEmail: sarang.shravagi@phonepe.com, santosh.patil@phonepe.com
  - service: mercedes-thread-pool
    ownerEmail: mohammed.irfanulla@phonepe.com, nayanava.de@phonepe.com, offers-oncall@phonepe.com

mailConfig:
  from: noreply@phonepe.com
  host: stg-smtp001.phonepe.nm2
  port: 25
  defaultOwnersEnabled: true
  defaultOwnersEmails: nitish.goyal@phonepe.com, mudit@phonepe.com, santanu@phonepe.com, phaneesh@phonepe.com

logging:
  level: INFO
